import { useState } from 'react'
import { Pencil, Trash2, Check, X } from 'lucide-react'
import { useDataStore } from '../../data/repo.ts'
import type { CostCenter } from '../../core/costCenters.ts'
import type { ExpenseTemplate } from '../../core/expenseCatalog.ts'
import { Btn, Field, inputCls, useToast } from '../components/ui.tsx'

const card = 'rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-card-dark'
const emptyTemplate: Omit<ExpenseTemplate, 'id' | 'isActive'> = { code: '', nameAr: '', accountCode: '5108', taxTreatment: 'exempt', taxPercent: 0, settlement: 'payable_later', affectsProfit: true, landedCostAllocation: 'none', notes: '' }

export function CostCentersPage() {
  const toast = useToast()
  const { costCenters, addCostCenter, updateCostCenter, removeCostCenter, expenseTemplates, addExpenseTemplate, updateExpenseTemplate, removeExpenseTemplate } = useDataStore()
  const [tab, setTab] = useState<'centers' | 'templates'>('centers')
  const [center, setCenter] = useState({ code: '', nameAr: '', notes: '' })
  const [editingCenter, setEditingCenter] = useState<number | null>(null)
  const [template, setTemplate] = useState(emptyTemplate)
  const [editingTemplate, setEditingTemplate] = useState<number | null>(null)
  const run = (fn: () => void) => { try { fn(); toast.show('تم الحفظ بنجاح ✓') } catch (error) { toast.show((error as Error).message, 'error') } }
  const resetCenter = () => { setCenter({ code: '', nameAr: '', notes: '' }); setEditingCenter(null) }
  const resetTemplate = () => { setTemplate(emptyTemplate); setEditingTemplate(null) }
  const saveCenter = () => run(() => { if (editingCenter == null) addCostCenter(center); else updateCostCenter(editingCenter, center); resetCenter() })
  const saveTemplate = () => run(() => { if (editingTemplate == null) addExpenseTemplate(template); else updateExpenseTemplate(editingTemplate, template); resetTemplate() })
  const editCenter = (row: CostCenter) => { setEditingCenter(row.id); setCenter({ code: row.code, nameAr: row.nameAr, notes: row.notes }) }
  const editTemplate = (row: ExpenseTemplate) => { setEditingTemplate(row.id); setTemplate({ code: row.code, nameAr: row.nameAr, accountCode: row.accountCode, taxTreatment: row.taxTreatment, taxPercent: row.taxPercent, settlement: row.settlement, affectsProfit: row.affectsProfit, landedCostAllocation: row.landedCostAllocation, notes: row.notes }) }
  return <div className="space-y-4" dir="rtl">
    <header><h1 className="text-2xl font-black">مراكز التكلفة وبنود المصروف</h1><p className="text-sm text-slate-500 mt-1">المركز العام مستقل عن المشروع وعن مركز تكلفة السيارة/الأصل. بنود المصروف قوالب قابلة لإعادة الاستخدام ولا تنشئ حركة مالية وحدها.</p></header>
    <div className="flex gap-2"><button className={`px-4 py-2 rounded-xl text-sm font-bold ${tab === 'centers' ? 'bg-brand-600 text-white' : 'bg-slate-100 dark:bg-slate-800'}`} onClick={() => setTab('centers')}>مراكز التكلفة العامة ({costCenters.length})</button><button className={`px-4 py-2 rounded-xl text-sm font-bold ${tab === 'templates' ? 'bg-brand-600 text-white' : 'bg-slate-100 dark:bg-slate-800'}`} onClick={() => setTab('templates')}>بنود المصروف ({expenseTemplates.length})</button></div>
    {tab === 'centers' ? <>
      <section className={`${card} p-4 space-y-3`}><h2 className="font-black">{editingCenter == null ? 'إضافة مركز تكلفة' : 'تعديل مركز تكلفة'}</h2><div className="grid md:grid-cols-3 gap-3"><Field label="الكود"><input className={inputCls} value={center.code} onChange={e => setCenter({ ...center, code: e.target.value })} placeholder="CC-SALES" /></Field><Field label="الاسم"><input className={inputCls} value={center.nameAr} onChange={e => setCenter({ ...center, nameAr: e.target.value })} placeholder="فرع المنصورة" /></Field><Field label="ملاحظات"><input className={inputCls} value={center.notes} onChange={e => setCenter({ ...center, notes: e.target.value })} /></Field></div><div className="flex gap-2"><Btn onClick={saveCenter}><Check size={15} /> {editingCenter == null ? 'إضافة' : 'حفظ التعديل'}</Btn>{editingCenter != null && <Btn variant="ghost" onClick={resetCenter}><X size={15} /> إلغاء</Btn>}</div></section>
      <section className={`${card} overflow-hidden`}><div className="p-4 border-b font-black">المراكز المسجلة</div>{costCenters.length === 0 ? <div className="p-8 text-center text-slate-400">لا توجد مراكز تكلفة عامة بعد.</div> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{costCenters.map(row => <div key={row.id} className="p-3 flex items-center gap-3"><span className={`w-2 h-2 rounded-full ${row.isActive ? 'bg-emerald-500' : 'bg-slate-400'}`} /><div className="flex-1"><b className="font-mono text-sm">{row.code}</b><span className="mx-2">—</span><span>{row.nameAr}</span>{row.notes && <p className="text-xs text-slate-400">{row.notes}</p>}</div><span className="text-xs text-slate-500">{row.isActive ? 'نشط' : 'معطل'}</span><button className="p-2 text-slate-500 hover:text-brand-600" onClick={() => editCenter(row)} title="تعديل"><Pencil size={15} /></button><button className="p-2 text-slate-500 hover:text-amber-600" onClick={() => run(() => updateCostCenter(row.id, { isActive: !row.isActive }))} title={row.isActive ? 'تعطيل' : 'تفعيل'}>{row.isActive ? <X size={15} /> : <Check size={15} />}</button><button className="p-2 text-rose-500" onClick={() => run(() => removeCostCenter(row.id))} title="حذف"><Trash2 size={15} /></button></div>)}</div>}</section>
    </> : <>
      <section className={`${card} p-4 space-y-3`}><h2 className="font-black">{editingTemplate == null ? 'إضافة بند مصروف قابل لإعادة الاستخدام' : 'تعديل بند المصروف'}</h2><div className="grid md:grid-cols-4 gap-3"><Field label="الكود"><input className={inputCls} value={template.code} onChange={e => setTemplate({ ...template, code: e.target.value })} placeholder="FREIGHT" /></Field><Field label="الاسم"><input className={inputCls} value={template.nameAr} onChange={e => setTemplate({ ...template, nameAr: e.target.value })} placeholder="نولون ونقل" /></Field><Field label="حساب المصروف"><input className={inputCls} value={template.accountCode} onChange={e => setTemplate({ ...template, accountCode: e.target.value })} placeholder="5108" /></Field><Field label="نسبة الضريبة"><input className={inputCls} type="number" min="0" max="100" value={template.taxPercent} onChange={e => setTemplate({ ...template, taxPercent: Number(e.target.value) })} /></Field></div><div className="grid md:grid-cols-4 gap-3"><Field label="المعاملة الضريبية"><select className={inputCls} value={template.taxTreatment} onChange={e => setTemplate({ ...template, taxTreatment: e.target.value as typeof template.taxTreatment })}><option value="exempt">معفى</option><option value="exclusive">إضافية</option><option value="inclusive">شاملة</option></select></Field><Field label="التسوية الافتراضية"><select className={inputCls} value={template.settlement} onChange={e => setTemplate({ ...template, settlement: e.target.value as typeof template.settlement })}><option value="payable_later">مستحق لاحقاً</option><option value="paid_now">مدفوع الآن</option></select></Field><Field label="التحميل على البنود"><select className={inputCls} value={template.landedCostAllocation} onChange={e => setTemplate({ ...template, landedCostAllocation: e.target.value as typeof template.landedCostAllocation })}><option value="none">لا يحمّل</option><option value="value">بالقيمة</option><option value="quantity">بالكمية</option><option value="equal">بالتساوي</option></select></Field><label className="flex items-center gap-2 text-sm pt-6"><input type="checkbox" checked={template.affectsProfit} onChange={e => setTemplate({ ...template, affectsProfit: e.target.checked })} /> يؤثر على الربحية</label></div><Field label="ملاحظات"><input className={inputCls} value={template.notes} onChange={e => setTemplate({ ...template, notes: e.target.value })} /></Field><div className="flex gap-2"><Btn onClick={saveTemplate}><Check size={15} /> {editingTemplate == null ? 'إضافة' : 'حفظ التعديل'}</Btn>{editingTemplate != null && <Btn variant="ghost" onClick={resetTemplate}><X size={15} /> إلغاء</Btn>}</div></section>
      <section className={`${card} overflow-hidden`}><div className="p-4 border-b font-black">البنود المسجلة</div>{expenseTemplates.length === 0 ? <div className="p-8 text-center text-slate-400">لا توجد بنود قابلة لإعادة الاستخدام بعد.</div> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{expenseTemplates.map(row => <div key={row.id} className="p-3 flex items-center gap-3"><span className={`w-2 h-2 rounded-full ${row.isActive ? 'bg-emerald-500' : 'bg-slate-400'}`} /><div className="flex-1"><b className="font-mono text-sm">{row.code}</b><span className="mx-2">—</span><span>{row.nameAr}</span><span className="text-xs text-slate-400 mx-2">حساب {row.accountCode}</span></div><button className="p-2 text-slate-500 hover:text-brand-600" onClick={() => editTemplate(row)}><Pencil size={15} /></button><button className="p-2 text-slate-500 hover:text-amber-600" onClick={() => run(() => updateExpenseTemplate(row.id, { isActive: !row.isActive }))}>{row.isActive ? <X size={15} /> : <Check size={15} />}</button><button className="p-2 text-rose-500" onClick={() => run(() => removeExpenseTemplate(row.id))}><Trash2 size={15} /></button></div>)}</div>}</section>
    </>}
  </div>
}
