import { useMemo, useState } from 'react'
import { CreditCard, Plus, Pencil, Ban, Trash2 } from 'lucide-react'
import { useDataStore } from '../../data/repo.ts'
import { nextTerminalCode, type PaymentTerminal, type PaymentTerminalStatus } from '../../core/paymentTerminals.ts'
import { summarizeTerminalTransactions } from '../../core/paymentTerminalReport.ts'
import { Btn, Field, Modal, inputCls, useToast } from '../components/ui.tsx'

const blank = (): PaymentTerminal => ({ id: crypto.randomUUID(), code: '', nameAr: '', providerName: '', branchId: '', settlementAccountCode: '', terminalId: '', merchantId: '', serialNumber: '', status: 'active' })
export function PaymentTerminalsPage() {
  const { paymentTerminals, paymentTerminalTransactions, branches, treasuries, addPaymentTerminal, updatePaymentTerminal, removePaymentTerminal } = useDataStore()
  const toast = useToast(); const [open, setOpen] = useState(false); const [draft, setDraft] = useState<PaymentTerminal>(blank()); const [editing, setEditing] = useState(false)
  const report = useMemo(() => summarizeTerminalTransactions(paymentTerminalTransactions), [paymentTerminalTransactions])
  const edit = (terminal?: PaymentTerminal) => { setEditing(!!terminal); setDraft(terminal ? { ...terminal } : { ...blank(), code: nextTerminalCode(paymentTerminals.map((row) => row.code)), branchId: String(branches.find((row) => row.active)?.id ?? ''), settlementAccountCode: treasuries.find((row) => row.kind === 'bank')?.code ?? treasuries[0]?.code ?? '' }); setOpen(true) }
  const save = () => { try { if (editing) updatePaymentTerminal(draft.id, draft); else addPaymentTerminal(draft); setOpen(false); toast.show('تم حفظ ماكينة الدفع ✓') } catch (error) { toast.show((error as Error).message, 'error') } }
  const remove = (id: string) => { try { removePaymentTerminal(id); toast.show('تم حذف الماكينة') } catch (error) { toast.show((error as Error).message, 'error') } }
  return <div className="space-y-5">
    <div className="flex justify-between items-center"><div><h2 className="text-xl font-black">ماكينات الدفع الإلكتروني</h2><p className="text-sm text-slate-500">تعريف الماكينات وربطها بالفروع وحسابات التسوية</p></div><Btn onClick={() => edit()} disabled={!branches.length}><Plus size={16}/> ماكينة جديدة</Btn></div>
    {!branches.length && <div className="p-4 rounded-2xl bg-amber-50 text-amber-800">أنشئ فرعاً أولاً من إدارة الفروع قبل إضافة ماكينة دفع.</div>}
    <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{paymentTerminals.map((terminal) => { const totals = report.filter((row) => row.terminalId === terminal.id).reduce((sum, row) => sum + row.netMinor, 0); return <div key={terminal.id} className="rounded-3xl border p-5 bg-white dark:bg-card-dark space-y-3"><div className="flex justify-between"><span className="w-11 h-11 rounded-2xl bg-indigo-500 text-white grid place-items-center"><CreditCard/></span><span className="text-xs font-mono">{terminal.code}</span></div><div><b>{terminal.nameAr}</b><div className="text-xs text-slate-500">{terminal.providerName} · {terminal.terminalId}</div></div><div className="text-xs">الفرع: {branches.find((row) => String(row.id) === terminal.branchId)?.nameAr ?? terminal.branchId}</div><div className="text-xs">صافي العمليات: {totals} minor</div><div className="flex gap-2"><Btn variant="soft" onClick={() => edit(terminal)}><Pencil size={14}/> تعديل</Btn>{terminal.status === 'active' && <Btn variant="soft" onClick={() => updatePaymentTerminal(terminal.id, { status: 'suspended' })}><Ban size={14}/> إيقاف</Btn>}<Btn variant="danger" onClick={() => remove(terminal.id)}><Trash2 size={14}/></Btn></div></div>})}</div>
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'تعديل ماكينة الدفع' : 'إضافة ماكينة دفع'}><div className="grid sm:grid-cols-2 gap-3">
      <Field label="الكود"><input className={inputCls} value={draft.code} onChange={(e) => setDraft({ ...draft, code: e.target.value.toUpperCase() })}/></Field><Field label="الاسم"><input className={inputCls} value={draft.nameAr} onChange={(e) => setDraft({ ...draft, nameAr: e.target.value })}/></Field>
      <Field label="مزود الدفع"><input className={inputCls} value={draft.providerName} onChange={(e) => setDraft({ ...draft, providerName: e.target.value })}/></Field><Field label="Terminal ID"><input className={inputCls} value={draft.terminalId} onChange={(e) => setDraft({ ...draft, terminalId: e.target.value })}/></Field>
      <Field label="Merchant ID"><input className={inputCls} value={draft.merchantId ?? ''} onChange={(e) => setDraft({ ...draft, merchantId: e.target.value })}/></Field><Field label="الرقم التسلسلي"><input className={inputCls} value={draft.serialNumber ?? ''} onChange={(e) => setDraft({ ...draft, serialNumber: e.target.value })}/></Field>
      <Field label="الفرع"><select className={inputCls} value={draft.branchId} onChange={(e) => setDraft({ ...draft, branchId: e.target.value })}>{branches.filter((row) => row.active).map((row) => <option key={row.id} value={row.id}>{row.nameAr}</option>)}</select></Field><Field label="حساب التسوية"><select className={inputCls} value={draft.settlementAccountCode} onChange={(e) => setDraft({ ...draft, settlementAccountCode: e.target.value })}>{treasuries.map((row) => <option key={row.code} value={row.code}>{row.nameAr}</option>)}</select></Field>
      <Field label="الحالة"><select className={inputCls} value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value as PaymentTerminalStatus })}><option value="active">نشطة</option><option value="suspended">موقوفة</option><option value="retired">متقاعدة</option></select></Field>
    </div><div className="flex justify-end gap-2 mt-5"><Btn variant="soft" onClick={() => setOpen(false)}>إلغاء</Btn><Btn onClick={save}>حفظ</Btn></div></Modal>
  </div>
}
