import { useMemo, useState } from 'react'
import { CreditCard, Plus, Pencil, Ban, Trash2 } from 'lucide-react'
import { useDataStore } from '../../data/repo.ts'
import { nextTerminalCode, type PaymentTerminal, type PaymentTerminalStatus } from '../../core/paymentTerminals.ts'
import { summarizeTerminalTransactions, terminalReportCsv } from '../../core/paymentTerminalReport.ts'
import { Btn, Field, Modal, inputCls, useToast } from '../components/ui.tsx'
import { useAppStore } from '../../stores/app.store.ts'
import { getCountry } from '../../core/countries.ts'
import { toMinor } from '../../core/money.ts'

const blank = (): PaymentTerminal => ({ id: crypto.randomUUID(), code: '', nameAr: '', providerName: '', branchId: '', settlementAccountCode: '', terminalId: '', merchantId: '', serialNumber: '', status: 'active' })
export function PaymentTerminalsPage() {
  const { paymentTerminals, paymentTerminalTransactions, paymentTerminalSettlements, branches, treasuries, appUsers, currentUserId, addPaymentTerminal, updatePaymentTerminal, removePaymentTerminal, recordPaymentTerminalSettlement } = useDataStore()
  const toast = useToast(); const [open, setOpen] = useState(false); const [draft, setDraft] = useState<PaymentTerminal>(blank()); const [editing, setEditing] = useState(false)
  const [from, setFrom] = useState(''); const [to, setTo] = useState('')
  const [settleTerminalId, setSettleTerminalId] = useState<string | null>(null); const [fee, setFee] = useState(''); const [feeTax, setFeeTax] = useState(''); const [deposit, setDeposit] = useState('')
  const decimals = Number((useAppStore.getState().setup.countryCode && getCountry(useAppStore.getState().setup.countryCode!)?.currency.decimals) || 2)
  const settledIds = new Set(paymentTerminalSettlements.flatMap((row) => row.transactionIds))
  const unsettled = paymentTerminalTransactions.filter((row) => row.terminalId === settleTerminalId && !settledIds.has(row.id))
  const unsettledGross = unsettled.reduce((sum, row) => sum + (row.kind === 'charge' ? row.amountMinor : -row.amountMinor), 0)
  const report = useMemo(() => summarizeTerminalTransactions(paymentTerminalTransactions, from ? `${from}T00:00:00` : undefined, to ? `${to}T23:59:59.999` : undefined), [paymentTerminalTransactions, from, to])
  const edit = (terminal?: PaymentTerminal) => { setEditing(!!terminal); setDraft(terminal ? { ...terminal } : { ...blank(), code: nextTerminalCode(paymentTerminals.map((row) => row.code)), branchId: String(branches.find((row) => row.active)?.id ?? ''), settlementAccountCode: treasuries.find((row) => row.kind === 'bank')?.code ?? treasuries[0]?.code ?? '' }); setOpen(true) }
  const save = () => { try { if (editing) updatePaymentTerminal(draft.id, draft); else addPaymentTerminal(draft); setOpen(false); toast.show('تم حفظ ماكينة الدفع ✓') } catch (error) { toast.show((error as Error).message, 'error') } }
  const remove = (id: string) => { try { removePaymentTerminal(id); toast.show('تم حذف الماكينة') } catch (error) { toast.show((error as Error).message, 'error') } }
  const settle = () => { try { if (!settleTerminalId) return; recordPaymentTerminalSettlement({ id: crypto.randomUUID(), terminalId: settleTerminalId, bankAccountCode: paymentTerminals.find((row) => row.id === settleTerminalId)?.settlementAccountCode ?? '', transactionIds: unsettled.map((row) => row.id), settledAt: new Date().toISOString(), userId: currentUserId ?? 0, grossMinor: unsettledGross, feeMinor: toMinor(fee || '0', decimals), feeTaxMinor: toMinor(feeTax || '0', decimals), depositedMinor: toMinor(deposit || '0', decimals) }); setSettleTerminalId(null); toast.show('تم حفظ دفعة التسوية ✓') } catch (error) { toast.show((error as Error).message, 'error') } }
  return <div className="space-y-5">
    <div className="flex justify-between items-center"><div><h2 className="text-xl font-black">ماكينات الدفع الإلكتروني</h2><p className="text-sm text-slate-500">تعريف الماكينات وربطها بالفروع وحسابات التسوية</p></div><Btn onClick={() => edit()} disabled={!branches.length}><Plus size={16}/> ماكينة جديدة</Btn></div>
    {!branches.length && <div className="p-4 rounded-2xl bg-amber-50 text-amber-800">أنشئ فرعاً أولاً من إدارة الفروع قبل إضافة ماكينة دفع.</div>}
    <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{paymentTerminals.map((terminal) => { const totals = report.filter((row) => row.terminalId === terminal.id).reduce((sum, row) => sum + row.netMinor, 0); return <div key={terminal.id} className="rounded-3xl border p-5 bg-white dark:bg-card-dark space-y-3"><div className="flex justify-between"><span className="w-11 h-11 rounded-2xl bg-indigo-500 text-white grid place-items-center"><CreditCard/></span><span className="text-xs font-mono">{terminal.code}</span></div><div><b>{terminal.nameAr}</b><div className="text-xs text-slate-500">{terminal.providerName} · {terminal.terminalId}</div></div><div className="text-xs">الفرع: {branches.find((row) => String(row.id) === terminal.branchId)?.nameAr ?? terminal.branchId}</div><div className="text-xs">صافي العمليات: {totals} minor</div><div className="flex gap-2"><Btn variant="soft" onClick={() => { setSettleTerminalId(terminal.id); const ids = new Set(paymentTerminalSettlements.flatMap((row) => row.transactionIds)); const gross = paymentTerminalTransactions.filter((row) => row.terminalId === terminal.id && !ids.has(row.id)).reduce((sum, row) => sum + (row.kind === 'charge' ? row.amountMinor : -row.amountMinor), 0); setFee(''); setFeeTax(''); setDeposit(String(gross / 10 ** decimals)) }}>تسوية</Btn><Btn variant="soft" onClick={() => edit(terminal)}><Pencil size={14}/> تعديل</Btn>{terminal.status === 'active' && <Btn variant="soft" onClick={() => updatePaymentTerminal(terminal.id, { status: 'suspended' })}><Ban size={14}/> إيقاف</Btn>}<Btn variant="danger" onClick={() => remove(terminal.id)}><Trash2 size={14}/></Btn></div></div>})}</div>
    <section className="rounded-3xl border bg-white dark:bg-card-dark p-5 space-y-3"><h3 className="font-black">دفعات التسوية</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="text-right p-2">التاريخ</th><th>الماكينة</th><th>الإجمالي</th><th>العمولة وضريبتها</th><th>إيداع البنك</th><th>الفرق</th></tr></thead><tbody>{[...paymentTerminalSettlements].reverse().map((row) => <tr key={row.id} className="border-t"><td className="p-2">{row.settledAt.slice(0, 10)}</td><td className="text-center">{paymentTerminals.find((item) => item.id === row.terminalId)?.nameAr ?? row.terminalId}</td><td className="text-center">{row.grossMinor}</td><td className="text-center">{row.feeMinor + row.feeTaxMinor}</td><td className="text-center">{row.depositedMinor}</td><td className={`text-center font-black ${row.differenceMinor ? 'text-rose-500' : 'text-emerald-600'}`}>{row.differenceMinor}</td></tr>)}</tbody></table>{!paymentTerminalSettlements.length && <div className="text-center text-slate-400 py-6">لم تُسجل دفعات تسوية بعد</div>}</div></section>
    <section className="rounded-3xl border bg-white dark:bg-card-dark p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-black">تقرير التحصيل حسب الماكينة والمستخدم</h3><div className="flex gap-2"><Btn variant="soft" onClick={() => { const blob = new Blob([terminalReportCsv(report)], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `payment-terminals-${from || 'all'}-${to || 'all'}.csv`; anchor.click(); URL.revokeObjectURL(url) }}>CSV</Btn><input aria-label="من تاريخ" type="date" className={inputCls} value={from} onChange={(e) => setFrom(e.target.value)}/><input aria-label="إلى تاريخ" type="date" className={inputCls} value={to} onChange={(e) => setTo(e.target.value)}/></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-slate-500"><th className="text-right p-2">الماكينة</th><th>الفرع</th><th>المستخدم</th><th>التحصيل</th><th>الرد</th><th>الإلغاء</th><th>الصافي</th><th>العمليات</th></tr></thead><tbody>{report.map((row) => <tr key={`${row.terminalId}:${row.branchId}:${row.userId}`} className="border-t"><td className="p-2">{paymentTerminals.find((item) => item.id === row.terminalId)?.nameAr ?? row.terminalId}</td><td className="text-center">{branches.find((item) => String(item.id) === row.branchId)?.nameAr ?? row.branchId}</td><td className="text-center">{appUsers.find((item) => item.id === row.userId)?.nameAr ?? row.userId}</td><td className="text-center">{row.chargeMinor}</td><td className="text-center">{row.refundMinor}</td><td className="text-center">{row.voidMinor}</td><td className="text-center font-black">{row.netMinor}</td><td className="text-center">{row.transactionCount}</td></tr>)}</tbody></table>{!report.length && <div className="text-center text-slate-400 py-8">لا توجد عمليات في الفترة المحددة</div>}</div></section>
    <Modal open={settleTerminalId != null} onClose={() => setSettleTerminalId(null)} title="تسوية ماكينة الدفع"><div className="space-y-3"><div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800">عمليات غير مسواة: <b>{unsettled.length}</b> · الإجمالي: <b>{unsettledGross / 10 ** decimals}</b></div><Field label="عمولة المزود"><input className={inputCls} type="number" min="0" value={fee} onChange={(e) => setFee(e.target.value)}/></Field><Field label="ضريبة العمولة"><input className={inputCls} type="number" min="0" value={feeTax} onChange={(e) => setFeeTax(e.target.value)}/></Field><Field label="المبلغ المودع بالبنك"><input className={inputCls} type="number" min="0" value={deposit} onChange={(e) => setDeposit(e.target.value)}/></Field><div className="flex justify-end gap-2"><Btn variant="ghost" onClick={() => setSettleTerminalId(null)}>إلغاء</Btn><Btn disabled={!unsettled.length} onClick={settle}>حفظ التسوية</Btn></div></div></Modal>
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'تعديل ماكينة الدفع' : 'إضافة ماكينة دفع'}><div className="grid sm:grid-cols-2 gap-3">
      <Field label="الكود"><input className={inputCls} value={draft.code} onChange={(e) => setDraft({ ...draft, code: e.target.value.toUpperCase() })}/></Field><Field label="الاسم"><input className={inputCls} value={draft.nameAr} onChange={(e) => setDraft({ ...draft, nameAr: e.target.value })}/></Field>
      <Field label="مزود الدفع"><input className={inputCls} value={draft.providerName} onChange={(e) => setDraft({ ...draft, providerName: e.target.value })}/></Field><Field label="Terminal ID"><input className={inputCls} value={draft.terminalId} onChange={(e) => setDraft({ ...draft, terminalId: e.target.value })}/></Field>
      <Field label="Merchant ID"><input className={inputCls} value={draft.merchantId ?? ''} onChange={(e) => setDraft({ ...draft, merchantId: e.target.value })}/></Field><Field label="الرقم التسلسلي"><input className={inputCls} value={draft.serialNumber ?? ''} onChange={(e) => setDraft({ ...draft, serialNumber: e.target.value })}/></Field>
      <Field label="الفرع"><select className={inputCls} value={draft.branchId} onChange={(e) => setDraft({ ...draft, branchId: e.target.value })}>{branches.filter((row) => row.active).map((row) => <option key={row.id} value={row.id}>{row.nameAr}</option>)}</select></Field><Field label="حساب التسوية"><select className={inputCls} value={draft.settlementAccountCode} onChange={(e) => setDraft({ ...draft, settlementAccountCode: e.target.value })}>{treasuries.map((row) => <option key={row.code} value={row.code}>{row.nameAr}</option>)}</select></Field>
      <Field label="الحالة"><select className={inputCls} value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value as PaymentTerminalStatus })}><option value="active">نشطة</option><option value="suspended">موقوفة</option><option value="retired">متقاعدة</option></select></Field>
    </div><div className="flex justify-end gap-2 mt-5"><Btn variant="soft" onClick={() => setOpen(false)}>إلغاء</Btn><Btn onClick={save}>حفظ</Btn></div></Modal>
  </div>
}
